apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "crud"
        metrics_path: "/metrics"
        scrape_interval: 3s
        static_configs:
        - targets: ["crud-service:80"]