apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "crud"
        metrics_path: "/metrics"
        scrape_interval: 3s
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - default
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: job
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex: '80'
          action: keep