{
 "title": "Métricas",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"crud-service\"}[30s]) * 100",
     "legendFormat": "Pod {{instance}}"
    }
   ]
  },
  {
   "title": "Produtos Criados",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(webapimetric{method=\"POST\", endpoint=\"/Produto/Create\", job=\"crud-service\"})",
     "legendFormat": "Quant."
    }
   ]
  },
  {
   "title": "Produtos Editados",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(webapimetric{method=\"POST\", endpoint=~\"/Produto/Edit/[0-9]+.*\", job=\"crud-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória (GB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "process_private_memory_bytes{job=\"crud-service\"} / 1024 / 1024 / 1024",
     "legendFormat": "Pod {{instance}}"
    }
   ]
  },
  {
   "title": "Produtos Deletados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(webapimetric{method=\"POST\", endpoint=~\"/Produto/Delete/[0-9]+.*\", job=\"crud-service\"})",
     "legendFormat": "Quant."
    }
   ]
  }
 ]
}