apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deployment
  labels:
    app: crud-app
spec:  
  replicas: 4
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
        - name: crud-container
          image: charlesmendes13/crud
          env:
            - name: SERVER
              value: "sql-service"
            - name: PORT
              value: "1433"
            - name: DATABASE
              value: "crud"
            - name: USER
              value: "SA"
            - name: PASSWORD
              value: "Str0ngPassw0rd123!"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10