apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-deployment
  labels:
    app: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      containers:
        - name: jmeter-container
          image: egaillardon/jmeter
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: jmeter-config
              mountPath: /jmeter/scripts
      volumes:
        - name: jmeter-config
          configMap:
            name: jmeter-config

# kubectl get pods
# kubectl exec -it <pod name> -- jmeter -n -t /jmeter/scripts/crud.jmx