apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-deployment
  labels:
    app: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
      - name: prom-container
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prom-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prom-volume
          mountPath: /prometheus
      volumes:
      - name: prom-config
        configMap:
          name: prom-config
      - name: prom-volume
        persistentVolumeClaim:
          claimName: prom-volume
