apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  labels:
    app: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
        - name: sql-container
          image: mcr.microsoft.com/azure-sql-edge
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Str0ngPa$$w0rd"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: sql-volume
              mountPath: /var/opt/mssql
      volumes:
      - name: sql-volume
        persistentVolumeClaim:
          claimName: sql-volume