global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: "crud"
    metrics_path: "/metrics"
    scrape_interval: 3s
    static_configs:
    - targets: ["crud-service:80"]

# kubectl create configmap prom-config --from-file=prometheus.yml